<!DOCTYPE books [
	<!ELEMENT books ANY>
	<!ELEMENT book ANY>
	<!ATTLIST book id ID #REQUIRED>
	<!ATTLIST book title CDATA "Default Title">
	<!ELEMENT page ANY>]>

<books>
	<book id="MasterOfTheMoon" title="Master of the Moon (Pisces)">
		<page>1. ONE MORE FOR THE ROAD</page>
		<page>2. MASTER OF THE MOON</page>
		<page>3. THE END OF THE WORLD</page>
		<page>4. SHIVERS</page>
		<page>ETC.</page>
	</book>
</books>